name: qcbo
channels:
  - conda-forge
dependencies:
  - python=3.11
  # core sci stack
  - numpy=1.26.*
  - scipy=1.16.*
  - scikit-learn>=1.3
  - pandas
  - matplotlib
  - ipykernel
  - ipywidgets
  - tqdm
  # torch / botorch
  - pytorch=2.2.*
  - gpytorch
  - botorch
  # qiskit (known-good versions)
  - qiskit=1.4.1
  - qiskit-machine-learning=0.8.2
  - qiskit-algorithms=0.3.1
  - qiskit-ibm-runtime=0.39.0
  - pip
  - pip:
      - qiskit-aer==0.17.0
      - pennylane==0.42.2
      - pennylane-lightning